spring:
  application:
    name: CONFIGDEFAULT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8588/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
